using System;
using System.Collections.Generic;
using System.Text;

namespace StellarGK2._0.Host
{
    public partial class PacketHandler
    {
        // Method, PacketFormat & CallHandler (can be autogenerated)
        private static readonly Dictionary<int, Func<RawPacket, IServiceProvider, object>> CommandsMapper = new()
        {
            //{ 1409, CommandMapping<SampleCommandHandler, SampleParams> },
            TemplateMappingsTemplate
        };
    }
}
