using System;
using System.Collections.Generic;
using System.Text;
using CommanderCS.Packets;

namespace CommanderCS.Packets
{
    public partial class PacketHandler
    {
        // Method, PacketFormat & CallHandler (can be autogenerated)
        private static readonly Dictionary<int, Func<ParamsPacket, IServiceProvider, object>> CommandsMapper = new()
        {
            //{ 1409, CommandMapping<SampleCommandHandler, SampleParams> },
            TemplateMappingsTemplate
        };
    }
}