namespace CommanderCSLibrary.Shared.Enum
{
    public enum EBattleResultMove
    {
        Undefined,
        WorldMap,
        MyTown,
        Challenge,
        NextStage,
        ReStart,
        Raid,
        Academy,
        Guild,
        UnitResearch,
        Situation,
        Annihilation,
        NextAnnihilation,
        WaveBattle,
        WaveDuel,
        WorldDuel,
        Conquest,
        CooperateBattle,
        EventBattle,
        EventBattleRetry,
        EventRaid,
        EventRaidRetry,
        InfinityBattle,
        InfinityBattleRetry,
        CommanderDetailScenarioInfo
    }
}