// Token: 0x02000F6B RID: 3947
namespace StellarGKLibrary.Enum
{
    public enum MultiplePopUpType
    {
        UNDEFINED, NOTENOUGH_GOLD, NOTENOUGH_CASH, NOTENOUGH_BLUEPRINT, COMMANDER_RENEWAL, UPGRADE_BUILDING_INSTANTLY, RECRUIT_COMMANDER, RECRUIT_COMMANDER_DELAY, RECRUIT_COMMANDER_DELAY_RENEWAL, NOTENOUGH_BULLET = 101, NOTENOUGH_EXPLOSIONTICKET, NOTENOUGH_SWEEPTICKET, NOTENOUGH_CHALLENGE = 105, NOTENOUGH_KEY, NOTENOUGH_CHIP, NOTENOUGH_SPEAK, NOTENOUGH_SKILL, RECHARGE_STAGETYPE1 = 201, RECHARGE_STAGETYPE2, RECRUIT_COMMANDER_REFRESH = 301, RESET_STACKSCORE = 401, NOTENOUGH_METROBANK = 601, NOTENOUGH_RING
    }
}