<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<RootNamespace>CommanderCS</RootNamespace>
		<EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
		<ApplicationIcon>crying.ico</ApplicationIcon>
		<OutputType>Exe</OutputType>
		<StartupObject>CommanderCS.Program</StartupObject>
		<UserSecretsId>0341be9c-b70c-45ba-a06c-56931dff1f55</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Remove="Resources\**" />
	  <Content Remove="Resources\**" />
	  <EmbeddedResource Remove="Resources\**" />
	  <None Remove="Resources\**" />
	</ItemGroup>
	
	<ItemGroup>
	  <Content Include="crying.ico" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="MongoDB.Bson" Version="3.2.0" />
		<PackageReference Include="MongoDB.Driver" Version="3.2.0" />
		<PackageReference Include="MongoDB.Driver.Core" Version="2.30.0" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
		<PackageReference Include="Portable.BouncyCastle" Version="1.9.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\CommanderCS.Library\CommanderCS.Library.csproj" />
		<ProjectReference Include="..\CommandHandlerMappingsSourceGenerator\CommandHandlerMappingsSourceGenerator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
	</ItemGroup>

	<ItemGroup>
	  <Content Update="wwwroot\**">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="wwwroot\" />
	</ItemGroup>
</Project>
